### ISSUE TITLE
[Bug]: CTRL + F does nothing

### ISSUE THREAD

**Issue by koopernick** [TheodoreChu/append-editor#146]
**Describe the bug**
I can't open the search box

**To Reproduce**

Installed => https://notes.theochu.com/p/mEyBECVK7i
Selected "Append Editor"
Selected "Monaco" in the settings" and saved.

**Expected behavior**
According to your FAQ, CTRL+F should open a search function

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Desktop client of Standartnotes (v3.8.18)

**Additional context**
Let me know if I missed something !

**Comment by arekm** [comment]
The same problem, standard notes 3.9.4 on macos (desktop client). Tried both "Monaco" and "CodeMirror".

ctrl+f does nothing, so I guess it's a generic bug. Lack of search is a major pain in editor.
