### ISSUE TITLE
[Bug]:  Unable to check the task check box when using the todo list

### ISSUE THREAD

**Issue by patgadget** [TheodoreChu/append-editor#98]
**Describe the bug**
I try the example in https://docs.theochu.com/append-editor/to-do-lists/
the to do list display wonderful.
But i cannot find a way to click into the check box to mark it done.
**Expected behavior**
I would like to be able to put a check mark into those nice little square.

**Screenshots**
![image](https://user-images.githubusercontent.com/1461231/103447606-6c70d180-4c5b-11eb-92cf-4b4b265da07f.png)

**Additional context**

I don't know if this is supported or not?
Thanks for the nice editor

**Comment by TheodoreChu** [comment]
Hi,
Thanks for bringing this up. Unfortunately, checking the task items is only available in the Dynamic editing mode. To turn the Dynamic editing mode on, click the Settings button on top, click Dynamic editing mode, then click Save. Then the task items will be clickable.

**Comment by patgadget** [comment]
Thanks this worked
